<a href="https://colab.research.google.com/github/uzair011/Advance-python/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### VECTORS


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
x = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(x)
print("X transpose is : \n", x.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
X transpose is : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print("Scalar addition", 4 + x)
print("Scalar subtraction", 4 - x)
print("Scalar multiplication", 4 * x)
print("Scalar division", 4 / x)

Scalar addition [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Scalar subtraction [[ 3  2  1]
 [ 0 -1 -2]
 [-3 -4 -5]]
Scalar multiplication [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
Scalar division [[4.         2.         1.33333333]
 [1.         0.8        0.66666667]
 [0.57142857 0.5        0.44444444]]


###Dot Product


In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Dot product", np.dot(x,y))
print("Dot product with @", x @ y)

Dot product 32
Dot product with @ 32


###MATRICES


In [11]:
# In Numpy matrix is a 2D array
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ones((2, 3))
z = np.array([[1, 2], [3, 4], [5, 6]])

print("x: ",x)
print()
print("y: ",y)
print()
print("z: ",z)

x:  [[1 2 3]
 [4 5 6]]

y:  [[1. 1. 1.]
 [1. 1. 1.]]

z:  [[1 2]
 [3 4]
 [5 6]]
