<a href="https://colab.research.google.com/github/uzair011/Advance-python/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### VECTORS


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
x = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(x)
print("X transpose is : \n", x.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
X transpose is : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("Scalar addition", 4 + x)
print("Scalar subtraction", 4 - x)
print("Scalar multiplication", 4 * x)
print("Scalar division", 4 / x)

Scalar addition [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Scalar subtraction [[ 3  2  1]
 [ 0 -1 -2]
 [-3 -4 -5]]
Scalar multiplication [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
Scalar division [[4.         2.         1.33333333]
 [1.         0.8        0.66666667]
 [0.57142857 0.5        0.44444444]]


###Dot Product


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Dot product", np.dot(x,y))
print("Dot product with @", x @ y)

Dot product 32
Dot product with @ 32


###MATRICES


In [4]:
# In Numpy matrix is a 2D array
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ones((2, 3))
z = np.array([[1, 2], [3, 4], [5, 6]])

print("x: ",x)
print()
print("y: ",y)
print()
print("z: ",z)

x:  [[1 2 3]
 [4 5 6]]

y:  [[1. 1. 1.]
 [1. 1. 1.]]

z:  [[1 2]
 [3 4]
 [5 6]]


In [5]:
### OPERATIONS

print("Element wise addition \n:", x + y)
print("Element wise subtraction \n:", x - y)
print("Element wise multiplication \n:", x * y)
print("Element wise divition \n:", x / y)

Element wise addition 
: [[2. 3. 4.]
 [5. 6. 7.]]
Element wise subtraction 
: [[0. 1. 2.]
 [3. 4. 5.]]
Element wise multiplication 
: [[1. 2. 3.]
 [4. 5. 6.]]
Element wise divition 
: [[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
### OPERATIONS

print("Scaler wise addition \n:", 5 + z)
print("Scaler wise subtraction \n:", 5 - z)
print("Scaler wise multiplication \n:", 5 * z)
print("Scaler wise divition \n:", 5 / z)

Scaler wise addition 
: [[ 6  7]
 [ 8  9]
 [10 11]]
Scaler wise subtraction 
: [[ 4  3]
 [ 2  1]
 [ 0 -1]]
Scaler wise multiplication 
: [[ 5 10]
 [15 20]
 [25 30]]
Scaler wise divition 
: [[5.         2.5       ]
 [1.66666667 1.25      ]
 [1.         0.83333333]]


In [6]:
x1 = np.reshape(np.arange(6), (3,2))
x2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
x3 = np.array([[2, 5, 2], [1, 2, 1]])
x4 = np.ones((2, 3))

y1 = np.array([1, 2, 3])
y2 = np.array([0.5, 0.5])

In [12]:
print("x1: ", x1)
print("")
print("x4: ", x4)
print("")
print("Using the matmul function for two matrices: ")
print(np.matmul(x1, x4))
print("------------ -------- -------------")

print("Using the dot function for two matrices: ")
print(np.dot(x1, x4))

print("Using @ for two matrices: ")
print(x1 @ x4)

x1:  [[0 1]
 [2 3]
 [4 5]]

x4:  [[1. 1. 1.]
 [1. 1. 1.]]

Using the matmul function for two matrices: 
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
------------ -------- -------------
Using the dot function for two matrices: 
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
Using @ for two matrices: 
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [15]:
print("Y1: ")
print(y1)
print("Using the matmul function for vec and mat: ")
print(np.matmul(y1, x1))
print("\n Using the dot function for vec and mat: ")
print(np.dot(y1, x1))
print("\n Using @ for vec and mat: ")
print(y1 @ x1)

Y1: 
[1 2 3]
Using the matmul function for vec and mat: 
[16 22]

 Using the dot function for vec and mat: 
[16 22]

 Using @ for vec and mat: 
[16 22]


TRANSPOSE
 => Transpose is an operation that flips all elements of a matrix along the diagonal.

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

print("\n x transpose is: \n", x.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 x transpose is: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


IDENTITY MATRIX
=> In linear algebra, one particular marrix acts very similarly to how 1 behaves for scalar numbers.

In [21]:
I = np.eye(3)
x = np.reshape(np.arange(9), (3, 3))
y = np.array([1, 2, 3])

print("I: \n", I)
print("x: \n", x)
print("y: \n", y)

I: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
y: 
 [1 2 3]


In [23]:
print("I @ x: \n",I @ x)
print("\nx @ I: \n", x @ I)
print("\nI @ y: \n", I @ y)
print("\ny @ I: \n", y @ I )

I @ x: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

x @ I: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

I @ y: 
 [1. 2. 3.]

y @ I: 
 [1. 2. 3.]
